version: "2"
services:
  php:
    container_name: php
    build: php
    ports:
      - "8080:8080"
    command: "php -S 0.0.0.0:8080 -t /var/www/html"
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html

  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: webdb
      MYSQL_PASSWORD: webdb
      MYSQL_ROOT_PASSWORD: webdb
      MYSQL_DATABASE: webdb
      
volumes:
  src:
